### ISSUE TITLE
segfault in `cd_window_device_changed_cb()` when turning monitors on

### ISSUE THREAD

**Issue by mkubecek** [hughsie/colord-gtk#22]
On a system with two monitors attached via DisplayPort, darktable crashes whenever I keep it running while I turn the monitors off and later on again. The stacktrace looks like this:

```
...
#3  0x00007f23eec04344 in cd_window_device_changed_cb (device=0x4757960 [CdClient], window=0x429ccd0 [CdDevice]) at ../libcolord-gtk/cd-window.c:303
...
#8  0x00007f23ef015729 in cd_client_dbus_signal_cb (proxy=<optimized out>, sender_name=<optimized out>, signal_name=<optimized out>, parameters=0x470f380, client=0x4757960 [CdClient]) at ../lib/colord/cd-client.c:274
        object_path_tmp = 0x4851f30 "/org/freedesktop/ColorManager/devices/xrandr_Eizo_Nanao_Corporation_EV2736W_22346112_mike_1000"
        device = 0x429ccd0
        profile = 0x0
        sensor = 0x0
...
```

The segfaults happen in `cd_window_device_changed_cb()`:
```
        /* no device set yet */
        if (window->priv->device == NULL)
                return;
```
because `window->priv` is an invalid pointer (`0xaaaaaaaaaaaaaaaa`) and further analysis revealed that the `window` in fact points to a different object than expected:
```
(gdb) frame 3
#3  0x00007f23eec04344 in cd_window_device_changed_cb (device=0x4757960 [CdClient], window=0x429ccd0 [CdDevice]) at ../libcolord-gtk/cd-window.c:303
303             if (window->priv->device == NULL)
(gdb) p *window
$10 = {parent = {g_type_instance = {g_class = 0x3068b00 [g_type: CdDevice]}, ref_count = 2, qdata = 0x0}, priv = 0xaaaaaaaaaaaaaaaa}
(gdb) p *device
$11 = {parent_instance = {g_type_instance = {g_class = 0x302c200 [g_type: CdClient]}, ref_count = 3, qdata = 0x4493980}}
```
so that `window->priv` is outside the `CdDevice` object.

These two pointers do not match what `cd_window_device_changed_cb()` expects but they do match what `device` and `client` are in frame 8:
```
(gdb) frame 8
#8  0x00007f23ef015729 in cd_client_dbus_signal_cb (proxy=<optimized out>, sender_name=<optimized out>, signal_name=<optimized out>, parameters=0x470f380, client=0x4757960 [CdClient]) at ../lib/colord/cd-client.c:274
274                     g_signal_emit (client, signals[SIGNAL_DEVICE_CHANGED], 0,
(gdb) p client
$13 = 0x4757960 [CdClient]
(gdb) p device
$14 = (CdDevice_autoptr) 0x429ccd0
```

AFAICS the relevant code did not change much for quite long and I'm not familiar enough with glib interfaces to be able to tell what is the problem or what the call should look like.

**Comment by hughsie** [comment]
@mkubecek can you try the fix in wip/hughsie/callback-fix please?

**Comment by mkubecek** [comment]
Works for me, there is no segfault with this patch. I only got messages like
```
(darktable:9517): libcolord-CRITICAL **: 19:21:15.439: cd_device_get_default_profile: assertion 'priv->proxy != NULL' failed
(darktable:9517): libcolord-CRITICAL **: 19:21:15.439: cd_profile_equal: assertion 'CD_IS_PROFILE (profile1)' failed
(darktable:9517): GLib-GObject-CRITICAL **: 19:21:15.439: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
```
repeated multiple times but these do not seem directly related and I think I have already seen them before.

Thank you for the quick response.

**Comment by hughsie** [comment]
@mkubecek can you try that branch again please for those new warnings? Thanks.

**Comment by mkubecek** [comment]
Most of the assert messages are gone now, I only got
```
(darktable:15369): libcolord-CRITICAL **: 11:48:27.576: cd_device_get_default_profile: assertion 'priv->proxy != NULL' failed
(darktable:15369): libcolord-CRITICAL **: 11:48:27.713: cd_device_get_default_profile: assertion 'priv->proxy != NULL' failed
(darktable:15369): libcolord-CRITICAL **: 11:48:27.713: cd_device_get_default_profile: assertion 'priv->proxy != NULL' failed
```
(with the previous version it was the three messages quoted above repeated 7 times).

**Comment by hughsie** [comment]
Okay; that's a colord issue; I'll look at that on Monday. In the meantime, lets merge that branch and get most of the important stuff done.
